name: darter_bloc
description: Flexible but case-specific architectures based on the BLoC pattern.
version: 0.0.2
homepage: https://darter.io
##repository: https://github.com/darter/darter_bloc
author: Eduardo del Palacio Lirola <eddydpyl@gmail.com>

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  rxdart: 0.27.7

dev_dependencies:
  test: 
