name: darter_bloc
description: Flexible but case-specific architectures based on the BLoC pattern.
version: 0.1.0
homepage: https://darter.io
repository: https://github.com/darter/darter_bloc

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  test: 
